// declaration of the class with the name MyClass
public class MyClass {

    // declaration of variables
    private String name;
    
    // declaration of the class constructor method
    public MyClass(String name, Integer age) {
        // body of the class constructor method
        this.name = name;
    }
    
    // declaration of the get method
    public String getName() {
        return this.name;
    }
    
    // declaration of the set method
    public void setName(String name) {
        this.name = name;
    }
}